## numpy基础知识

In [2]:
import numpy as np

### 1、数组

In [2]:
# 将list转化成数组
a = [1,2 ,3 ]
print(np.array(a))

[1 2 3]


In [8]:
b = np.array([[1,2,3], [2,3,4]])
print(b)
print(b.shape)
## 打印出第一行第三个元素
b[0,1]

[[1 2 3]
 [2 3 4]]
(2, 3)


2

In [11]:
# 创建（2,3）的矩阵,元素为0
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 创建（2,3）矩阵，元素都是1
d = np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 创建（2,3）矩阵，元素都是3
e = np.full((2,2), 3)
e

array([[3, 3],
       [3, 3]])

In [17]:
# 生成对角线元素为1的3*3矩阵,其余元素都为0
f =  np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# 生成（2,3）矩阵，元素取[0，1）之间的随机浮点数
g = np.random.random((3,2))
g

array([[0.20578415, 0.70455621],
       [0.6479671 , 0.11691438],
       [0.66661127, 0.35846933]])

In [62]:
# 生成（2,2）维度的矩阵，元素取[-5,5）之间的整数
h = np.random.randint(-5,5,size=(2,2))
h

array([[-1, -2],
       [ 3, -2]])

In [67]:
# 类似ones，元素值随机，不进行初始化
# 多次执行这个，得到的值是不变的。
i = np.empty((2,3,4))
i

array([[[5.28428816e-316, 7.41098469e-322, 0.00000000e+000,
         0.00000000e+000],
        [2.41907520e-312, 1.16095484e-028, 5.28595592e-085,
         1.01445441e+242],
        [3.75159209e-091, 6.84979043e+180, 9.14396616e+135,
         1.71352438e+214]],

       [[1.17149199e+214, 1.67793285e+243, 1.67793307e+243,
         8.03704417e-095],
        [9.03292329e+271, 9.08366793e+223, 7.98460089e+159,
         8.09291803e+175],
        [5.56218858e+180, 2.97912157e+228, 9.44872517e-143,
         1.67979709e+243]]])

In [61]:
# 元素是整型的
i_1 = np.empty([2,3],dtype=int)
i_1

array([[1651835066, 1864394092, 1886265458],
       [1868849966, 1701601909, 1886330924]])

In [68]:
# 数据类型
j = np.array([1,2,3], dtype=np.float64)
print(j.dtype)

float64


In [70]:
# 修改数据类型
int_arr = np.array([1,2,3,4,5])
print(int_arr.dtype,int_arr)
# 使用astype将float转换为int时小数部分被舍弃
float_arr = int_arr.astype(np.float64)
print(float_arr.dtype, float_arr)

int32 [1 2 3 4 5]
float64 [1. 2. 3. 4. 5.]


### 2、数组取值

In [71]:
k = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(k)
print(k.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [72]:
# 取k中前两行、第三第四列的数据
l = k[0:2,2:4].copy()
print(l)

[[3 4]
 [7 8]]


In [73]:
# 修改l中的值,
l[0,0]=111
l

array([[111,   4],
       [  7,   8]])

##### 2.1 、取出行数据

In [80]:
# 取出一整行数据，第二行
k_1 = k[1,:]
print(k_1.shape,k_1)
k_2 = k[1:2,:]  # 还是一个矩阵，和上面不一样
print(k_2.shape,k_2)
k_3 = k[[1], :]
print(k_3.shape,k_3)

(4,) [5 6 7 8]
(1, 4) [[5 6 7 8]]
(1, 4) [[5 6 7 8]]


#### 2.2 、取出列数据

In [82]:
# 取出k中第3列的元素
k_4 = k[:,2]
print(k_4.shape,k_4)
k_5 = k[:, 1:2] # 取出第2列数据，并作为矩阵返回
print(k_5.shape,k_5)

(3,) [ 3  7 11]
(3, 1) [[ 2]
 [ 6]
 [10]]


In [85]:
m = np.array([[1,2], [3, 4], [5, 6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
# 取出第一行、第二行、第三行中对应的第一列，第二列、第一列的数据
print(m[[0,1,2], [0,1,0]])
print(m[[0,1,2], [0,1,0]].shape)

[1 4 5]
(3,)


In [87]:
n = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
n_1 = np.array([0, 2,0,1])
print(n_1)
# 打印出（1,2,3，4）行对应的（0+1,2+1,0+1,1+1）列数据
print(n[np.arange(4), n_1])
# n中对应元素加1
n[np.arange(4), n_1]+=100
n

[0 2 0 1]
[ 1  6  7 11]


array([[101,   2,   3],
       [  4,   5, 106],
       [107,   8,   9],
       [ 10, 111,  12]])

In [93]:
# 判定元素大小,n中大于4的为true
n_2 = (n>4)
n_2

array([[ True, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [96]:
# 输出n中大于10的元素
n[n>10]

array([101, 106, 107, 111,  12])

更加高级的用法
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

###  3、数学运算

In [4]:
o = np.array([[1,2],[3,4]], dtype=np.float64)
p = np.array([[5,6],[7,8]], dtype=np.float64)
print(o)
print(p)
# 加法运算，其他加减乘除类似
print(np.add(o,p))
# 另一种写法
print(o+p)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [7]:
# 向量内积
# 对于二维矩阵，计算真正意义上的矩阵乘积
print(np.dot(o,p))
#  对于一维矩阵，计算两者的内积
o_1 = np.array([9,10])
p_1 =  np.array([11,12])
print(np.dot(o_1,p_1))

[[19. 22.]
 [43. 50.]]
219


In [10]:
# 转置矩阵
o_2 = np.array([[2,3],[4,5]])
o_2.T

(2, 2)


array([[2, 4],
       [3, 5]])

In [11]:
q = np.arange(16).reshape(2,2,4)
q

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
# transpose默认是转置矩阵
q_1 = q.transpose()
print(q_1)
print('-'*5)
# q的0轴和1轴交换 ，注意：第一个方括号“[]”为 0轴 ，第二个方括号为 1轴 
q_2 = q.transpose((1,0,2))
print(q_2)
print('-'*5)
# q的0轴和2轴交换位置
q_3 = q.transpose((2,1,0))
print(q_3)

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
-----
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
-----
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


q （图中2轴从下到上应该是0，1，2，3） ![](https://github.com/sisyphusking/daydayup/blob/master/matrix-transpose.png?raw=true)
q交换0轴和1轴(第一个方括号“[]”为 0轴 ，第二个方括号为 1轴 ) ![](https://github.com/sisyphusking/daydayup/blob/master/matrix-transpose-2.png?raw=true)

In [8]:
# 矩阵内元素求和
r = np.array([[1,2], [3,4]])
print(r)
# 各个元素相加
r1 = np.sum(r)
print(r1)
# 列元素相加
r2 = np.sum(r,axis=0)
print(r2)
# 行元素相加
r3 = np.sum(r,axis=1)
print(r3)
# 行元素求均值
r4 = np.mean(r,axis=1)
print(r4)

[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[1.5 3.5]


In [ ]:
# 