## numpy基础知识

In [2]:
import numpy as np

### 1、数组

In [2]:
# 将list转化成数组
a = [1,2 ,3 ]
print(np.array(a))

[1 2 3]


In [8]:
b = np.array([[1,2,3], [2,3,4]])
print(b)
print(b.shape)
## 打印出第一行第三个元素
b[0,1]

[[1 2 3]
 [2 3 4]]
(2, 3)


2

In [11]:
# 创建（2,3）的矩阵,元素为0
c = np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 创建（2,3）矩阵，元素都是1
d = np.ones((2,3))
d

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# 创建（2,3）矩阵，元素都是3
e = np.full((2,2), 3)
e

array([[3, 3],
       [3, 3]])

In [17]:
# 生成对角线元素为1的3*3矩阵,其余元素都为0
f =  np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# 生成（2,3）矩阵，元素取[0，1）之间的随机浮点数
g = np.random.random((3,2))
g

array([[0.20578415, 0.70455621],
       [0.6479671 , 0.11691438],
       [0.66661127, 0.35846933]])

In [62]:
# 生成（2,2）维度的矩阵，元素取[-5,5）之间的整数
h = np.random.randint(-5,5,size=(2,2))
h

array([[-1, -2],
       [ 3, -2]])

In [67]:
# 类似ones，元素值随机，不进行初始化
# 多次执行这个，得到的值是不变的。
i = np.empty((2,3,4))
i

array([[[5.28428816e-316, 7.41098469e-322, 0.00000000e+000,
         0.00000000e+000],
        [2.41907520e-312, 1.16095484e-028, 5.28595592e-085,
         1.01445441e+242],
        [3.75159209e-091, 6.84979043e+180, 9.14396616e+135,
         1.71352438e+214]],

       [[1.17149199e+214, 1.67793285e+243, 1.67793307e+243,
         8.03704417e-095],
        [9.03292329e+271, 9.08366793e+223, 7.98460089e+159,
         8.09291803e+175],
        [5.56218858e+180, 2.97912157e+228, 9.44872517e-143,
         1.67979709e+243]]])

In [61]:
# 元素是整型的
i_1 = np.empty([2,3],dtype=int)
i_1

array([[1651835066, 1864394092, 1886265458],
       [1868849966, 1701601909, 1886330924]])

In [68]:
# 数据类型
j = np.array([1,2,3], dtype=np.float64)
print(j.dtype)

float64


In [70]:
# 修改数据类型
int_arr = np.array([1,2,3,4,5])
print(int_arr.dtype,int_arr)
# 使用astype将float转换为int时小数部分被舍弃
float_arr = int_arr.astype(np.float64)
print(float_arr.dtype, float_arr)

int32 [1 2 3 4 5]
float64 [1. 2. 3. 4. 5.]


### 2、数组取值

In [71]:
k = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(k)
print(k.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [72]:
# 取k中前两行、第三第四列的数据
l = k[0:2,2:4].copy()
print(l)

[[3 4]
 [7 8]]


In [73]:
# 修改l中的值,
l[0,0]=111
l

array([[111,   4],
       [  7,   8]])

##### 2.1 、取出行数据

In [80]:
# 取出一整行数据，第二行
k_1 = k[1,:]
print(k_1.shape,k_1)
k_2 = k[1:2,:]  # 还是一个矩阵，和上面不一样
print(k_2.shape,k_2)
k_3 = k[[1], :]
print(k_3.shape,k_3)

(4,) [5 6 7 8]
(1, 4) [[5 6 7 8]]
(1, 4) [[5 6 7 8]]


#### 2.2 、取出列数据

In [82]:
# 取出k中第3列的元素
k_4 = k[:,2]
print(k_4.shape,k_4)
k_5 = k[:, 1:2] # 取出第2列数据，并作为矩阵返回
print(k_5.shape,k_5)

(3,) [ 3  7 11]
(3, 1) [[ 2]
 [ 6]
 [10]]


In [85]:
m = np.array([[1,2], [3, 4], [5, 6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
# 取出第一行、第二行、第三行中对应的第一列，第二列、第一列的数据
print(m[[0,1,2], [0,1,0]])
print(m[[0,1,2], [0,1,0]].shape)

[1 4 5]
(3,)


In [87]:
n = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
n_1 = np.array([0, 2,0,1])
print(n_1)
# 打印出（1,2,3，4）行对应的（0+1,2+1,0+1,1+1）列数据
print(n[np.arange(4), n_1])
# n中对应元素加1
n[np.arange(4), n_1]+=100
n

[0 2 0 1]
[ 1  6  7 11]


array([[101,   2,   3],
       [  4,   5, 106],
       [107,   8,   9],
       [ 10, 111,  12]])

In [93]:
# 判定元素大小,n中大于4的为true
n_2 = (n>4)
n_2

array([[ True, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [96]:
# 输出n中大于10的元素
n[n>10]

array([101, 106, 107, 111,  12])

更加高级的用法
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

###  3、数学运算

In [4]:
o = np.array([[1,2],[3,4]], dtype=np.float64)
p = np.array([[5,6],[7,8]], dtype=np.float64)
print(o)
print(p)
# 加法运算，其他加减乘除类似
print(np.add(o,p))
# 另一种写法
print(o+p)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [7]:
# 向量内积
# 对于二维矩阵，计算真正意义上的矩阵乘积
print(np.dot(o,p))
#  对于一维矩阵，计算两者的内积
o_1 = np.array([9,10])
p_1 =  np.array([11,12])
print(np.dot(o_1,p_1))

[[19. 22.]
 [43. 50.]]
219


In [10]:
# 转置矩阵
o_2 = np.array([[2,3],[4,5]])
o_2.T

(2, 2)


array([[2, 4],
       [3, 5]])

In [11]:
q = np.arange(16).reshape(2,2,4)
q

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
# transpose默认是转置矩阵
q_1 = q.transpose()
print(q_1)
print('-'*5)
# q的0轴和1轴交换 ，注意：第一个方括号“[]”为 0轴 ，第二个方括号为 1轴 
q_2 = q.transpose((1,0,2))
print(q_2)
print('-'*5)
# q的0轴和2轴交换位置
q_3 = q.transpose((2,1,0))
print(q_3)

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]
-----
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
-----
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


q （图中2轴从下到上应该是0，1，2，3） ![](https://github.com/sisyphusking/daydayup/blob/master/matrix-transpose.png?raw=true)
q交换0轴和1轴(第一个方括号“[]”为 0轴 ，第二个方括号为 1轴 ) ![](https://github.com/sisyphusking/daydayup/blob/master/matrix-transpose-2.png?raw=true)

In [5]:
# 矩阵内元素求和
r = np.array([[1,2], [3,4]])
print(r)
# 各个元素相加
r1 = np.sum(r)
print(r1)
# 列元素相加
r2 = np.sum(r,axis=0)
print(r2)
# 行元素相加
r3 = np.sum(r,axis=1)
print(r3)
# 行元素求均值
r4 = np.mean(r,axis=1)
print(r4)


[[1 2]
 [3 4]]
10
[4 6]
[3 7]
[1.5 3.5]
None


In [29]:
#  np.where:当conditon的某个位置的为true时，输出x的对应位置的元素，否则选择y对应位置的元素
r5 = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
r6 = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
r7 = np.array([True, False, True, True, False])
print(np.where(r7, r5, r6))

[1.1 2.2 1.3 1.4 2.5]


### 4、广播

In [6]:
s =  np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
t = v = np.array([1, 0, 1])
print(s)
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [24]:
# 生成与a相似（形态和数据类型）的随机矩阵
s_1 = np.empty_like(s)
s_1

array([[122,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0]])

In [28]:
# 一般做法
for i in range(4):
    s_1[i,:] = s[i,:] + t
print(s_1)
# 广播
print(s.shape,t.shape)
s+t

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
(4, 3) (3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

![](https://github.com/sisyphusking/daydayup/blob/master/numpy-broadcast.png?raw=true)

In [32]:
# reshape
u =  np.arange(15)
print(u.reshape(5,3).shape)
# 如果我们在某一个维度上写上-1，numpy会帮我们自动推导出正确的维度
print(u.reshape(5,-1).shape)
# ravel将高维数组拉平
u_1 = u.reshape(5,3)
u_2 = u_1.ravel()
u_2

(5, 3)
(5, 3)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
v1 = np.array([[1, 2, 3], [4, 5, 6]])
v2 = np.array([[7, 8, 9], [10, 11, 12]])
# 合并两个数组 不同方向
v3 = np.concatenate([v1, v2], axis=0)
print(v3)
v4 = np.concatenate([v1, v2], axis=1)
print(v4)
# 堆叠也能起到相同的作用,垂直堆叠
v5 = np.vstack((v1,v2))
print(v5)
# 水平堆叠
v6 = np.hstack((v1,v2))
print(v6)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
#  读取文件
w = np.loadtxt('array_ex.txt', delimiter=',')
print(w)

In [43]:
w1 = np.arange(20).reshape(2,2,5)
print(w1)
# 保存
np.save('some_array', w1)
# 提取
w2 = np.load('some_array.npy')
print(w2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


###  5、用numpy写一个softmax

In [44]:
# 以给定的形状创建一个(10,10)的数组，并在数组中加入在[0,1]之间均匀分布的随机样本，然后元素乘以10 ，再加上1000
x = np.random.rand(10,10) * 10 + 1000
print(x)

[[1004.93241217 1000.30996603 1005.77189237 1007.84202054 1004.80344567
  1000.5646706  1002.94648962 1001.50811848 1008.73050257 1001.75616713]
 [1009.02925138 1009.4998451  1008.78188358 1005.02985148 1000.60801923
  1005.08101347 1003.43120945 1009.32578105 1003.2872178  1006.44823787]
 [1004.40550698 1002.77038198 1006.23936487 1008.68771137 1009.76447417
  1005.09098472 1001.79780087 1001.68018977 1009.29722199 1006.82451727]
 [1005.98252957 1001.93953883 1006.07027846 1004.17963251 1006.27483471
  1009.19066431 1006.68131536 1004.77500499 1000.91944586 1003.5150348 ]
 [1000.07256747 1007.06431159 1000.60789862 1000.44832402 1009.8680554
  1007.35525321 1005.62112708 1002.5876942  1002.92636906 1009.81148391]
 [1003.54742759 1009.69125704 1008.02777872 1002.08157329 1009.44866717
  1002.46062046 1002.42841807 1003.91644193 1001.59204917 1007.19189358]
 [1006.30576886 1000.31950193 1006.25613453 1001.8829354  1001.38710453
  1008.46342087 1009.2190241  1004.4369867  1003.2981644  1

In [46]:
# np.exp(m) 求出每一行中的最大值
x_row_max = x.max(axis=1).reshape(10,1)
print(x_row_max, x_row_max.shape)

[[1008.73050257]
 [1009.4998451 ]
 [1009.76447417]
 [1009.19066431]
 [1009.8680554 ]
 [1009.69125704]
 [1009.2190241 ]
 [1009.95859743]
 [1009.69812948]
 [1009.84050022]] (10, 1)


In [47]:
# x减去每一行最大值
x = x - x_row_max
print(x)

[[-3.79809039e+00 -8.42053654e+00 -2.95861019e+00 -8.88482023e-01
  -3.92705689e+00 -8.16583197e+00 -5.78401295e+00 -7.22238409e+00
   0.00000000e+00 -6.97433543e+00]
 [-4.70593713e-01  0.00000000e+00 -7.17961519e-01 -4.46999362e+00
  -8.89182587e+00 -4.41883163e+00 -6.06863565e+00 -1.74064051e-01
  -6.21262730e+00 -3.05160722e+00]
 [-5.35896718e+00 -6.99409218e+00 -3.52510930e+00 -1.07676280e+00
   0.00000000e+00 -4.67348944e+00 -7.96667330e+00 -8.08428440e+00
  -4.67252176e-01 -2.93995690e+00]
 [-3.20813474e+00 -7.25112548e+00 -3.12038585e+00 -5.01103180e+00
  -2.91582959e+00  0.00000000e+00 -2.50934894e+00 -4.41565932e+00
  -8.27121844e+00 -5.67562951e+00]
 [-9.79548793e+00 -2.80374381e+00 -9.26015678e+00 -9.41973138e+00
   0.00000000e+00 -2.51280219e+00 -4.24692833e+00 -7.28036120e+00
  -6.94168634e+00 -5.65714903e-02]
 [-6.14382946e+00  0.00000000e+00 -1.66347832e+00 -7.60968375e+00
  -2.42589869e-01 -7.23063658e+00 -7.26283897e+00 -5.77481511e+00
  -8.09920787e+00 -2.49936346e+00

In [48]:
# 返回e的x次方,每一个元素都求其指数函数
x_exp = np.exp(x)
print(x_exp, x_exp.shape)

[[2.24135321e-02 2.20296423e-04 5.18909855e-02 4.11279592e-01
  1.97015711e-02 2.84200106e-04 3.07634540e-03 7.30059817e-04
  1.00000000e+00 9.35587923e-04]
 [6.24631307e-01 1.00000000e+00 4.87745503e-01 1.14473889e-02
  1.37508356e-04 1.20483009e-02 2.31432862e-03 8.40243077e-01
  2.00396553e-03 4.72828691e-02]
 [4.70576379e-03 9.17285142e-04 2.94485885e-02 3.40696646e-01
  1.00000000e+00 9.33962252e-03 3.46830873e-04 3.08347120e-04
  6.26722026e-01 5.28680075e-02]
 [4.04319591e-02 7.09375551e-04 4.41401336e-02 6.66402383e-03
  5.41590823e-02 1.00000000e+00 8.13211668e-02 1.20865826e-02
  2.55773456e-04 3.42851003e-03]
 [5.57023660e-05 6.05828269e-02 9.51404078e-05 8.11078036e-05
  1.00000000e+00 8.10408287e-02 1.43081163e-02 6.88936673e-04
  9.66638139e-04 9.44998924e-01]
 [2.14668721e-03 1.00000000e+00 1.89478765e-01 4.95628577e-04
  7.84593234e-01 7.24059792e-04 7.01114761e-04 3.10477165e-03
  3.03779675e-04 8.21372655e-02]
 [5.42986864e-02 1.36454112e-04 5.16693986e-02 6.51594118e

In [49]:
# 每一行元素的指数函数相加
x_exp_row_sum = x_exp.sum(axis=1).reshape(10,1)
print(x_exp_row_sum, x_exp_row_sum.shape)

[[1.51053217]
 [3.02785425]
 [2.06535312]
 [1.24319661]
 [2.10281822]
 [2.06368531]
 [2.14628523]
 [2.30060028]
 [1.38715473]
 [1.19231374]] (10, 1)


In [50]:
# 每个元素都除以所在行的元素和
x_softmax = x_exp / x_exp_row_sum
print(x_softmax)

[[1.48381693e-02 1.45840272e-04 3.43527841e-02 2.72274633e-01
  1.30428014e-02 1.88145682e-04 2.03659707e-03 4.83312988e-04
  6.62018340e-01 6.19376364e-04]
 [2.06295038e-01 3.30266888e-01 1.61086190e-01 3.78069351e-03
  4.54144570e-05 3.97915486e-03 7.64346112e-04 2.77504466e-01
  6.61843459e-04 1.56159660e-02]
 [2.27843062e-03 4.44129933e-04 1.42583795e-02 1.64958061e-01
  4.84178706e-01 4.52204635e-03 1.67928123e-04 1.49295110e-04
  3.03445460e-01 2.55975635e-02]
 [3.25225783e-02 5.70606086e-04 3.55053524e-02 5.36039416e-03
  4.35643743e-02 8.04378000e-01 6.54129574e-02 9.72218116e-03
  2.05738541e-04 2.75781804e-03]
 [2.64893872e-05 2.88103015e-02 4.52442379e-05 3.85710009e-05
  4.75552280e-01 3.85391509e-02 6.80425735e-03 3.27625406e-04
  4.59686971e-04 4.49396393e-01]
 [1.04022023e-03 4.84570005e-01 9.18157262e-02 2.40166742e-04
  3.80190348e-01 3.50857657e-04 3.39739183e-04 1.50447922e-03
  1.47202519e-04 3.98012552e-02]
 [2.52989145e-02 6.35768769e-05 2.40738733e-02 3.03591578e

In [51]:
# 验证每一行元素相加是否等于1
print(x_softmax.sum(axis=1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
